examples/MOTD_Using_Eggs/src/acme.motd/setup.py
Renaming EnvisageCore -> Envisage caused the `MOTD_Using_Eggs` example to break.
=> Fix the install_requires field for the acme.motd plugin egg

envisage/plugins/remote_editor/communication/server.py
A trivial nitpick: `logging.info` should be `logger.info` here.
=> Fix an instance of logging.info that should have been logger.info

envisage/ui/tasks/tasks_application.py
As a newbie, I didn't specify a layout for the a window I created using TaskApplication.create_window. When I called Application.exit(), I get the following exception:
```
Traceback (most recent call last):
File "/data/home/rob/src/enthought/envisage/envisage/ui/tasks/tasks_application.py", line 247, in exit
self._prepare_exit()
File "/data/home/rob/src/enthought/envisage/envisage/ui/tasks/tasks_application.py", line 303, in _prepare_exit
self._save_state()
File "/data/home/rob/src/enthought/envisage/envisage/ui/tasks/tasks_application.py", line 351, in _save_state
window_layouts = [ w.get_window_layout() for w in self.windows ]
File "/data/home/rob/src/enthought/pyface/pyface/tasks/task_window.py", line 306, in get_window_layout
size_state=self.size_state)
AttributeError: 'TaskWindow' …
```
=> Fixes degenerate case where no layout is specified in create_window

envisage/ui/tasks/tasks_application.py, envisage/ui/tasks/tasks_plugin.py
@corranwebster 
This fixes some bad trait definitions from #76 as well as making it possible to create a `TasksApplication` including the `TasksPlugin` without creating a GUI.
=> Create tasks application without gui

envisage/plugins/ipython_kernel/internal_ipkernel.py
This very small update to the `connect_qtconsole` call, removing the use of the [deprecated](https://github.com/ipython/ipykernel/blob/master/ipykernel/connect.py#L157) option profile seems to fix https://github.com/enthought/envisage/issues/62 .
=> Remove use of deprecated "profile" kw in connect_qtconsole

envisage/developer/code_browser/code_browser.py, envisage/developer/code_browser/enclbr.py, envisage/plugins/text_editor/editor/text_editor.py, envisage/plugins/update_checker/tests/bare_app.py, envisage/ui/single_project/project.py
See enthought/traitsui#297 and enthought/traitsui#300.
=> Replace uses of 'file' and 'execfile' for Python 3 compatibility

envisage/ui/tasks/tasks_application.py
In Python3, pickle serializes to bytes so file has to be opened
in binary mode.
=> Fix task layout serialization under Python3

envisage/plugins/ipython_kernel/tests/test_internal_ipkernel.py
Importing from `IPython` is deprecated, and doesn't match the imports that we need for the code under test.
```
(canopy-data-ci)(edm)bash-3.2$ python -Wd
Enthought Deployment Manager -- https://www.enthought.com
Python 2.7.10 |Enthought, Inc. (x86_64)| (default, Jun 23 2016, 05:02:55) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import IPython.kernel
/Users/mdickinson/.edm/envs/canopy-data-ci/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
"You should import from ipykernel or jupyter_client instead.", ShimWarning)
```
=> Fix deprecated IPython import.

envisage/plugins/ipython_kernel/internal_ipkernel.py, envisage/plugins/ipython_kernel/tests/test_internal_ipkernel.py
Fixes #93.
Also fixes the imports at the top of the test module to skip tests correctly under unittest if `ipykernel` isn't available.
=> Stop the IOPubThread as part of IPython kernel shutdown.

envisage/plugins/ipython_kernel/internal_ipkernel.py
This PR replaces the `--matplotlib` that's used when starting the IPython kernel with `--gui`. This eliminates a dependence on the matplotlib package, and avoids some unpleasant import-order difficulties where the import of `matplotlib.pyplot` sets the IPython kernel event loop, preventing one from patching that event loop at import time. [See [this code](https://github.com/matplotlib/matplotlib/blob/v2.0.2/lib/matplotlib/pyplot.py#L166), for example]
=> Use --gui rather than --matplotlib when starting IPython kernel.

examples/plugins/tasks/attractors/model/lorenz.py, examples/plugins/tasks/attractors/model/rossler.py, examples/plugins/tasks/attractors/visualize_2d_task.py
- Do explicit adaptation when creating models for the 2d view
- Replace uses of the deprecated `adapts` function with the newer `register_factory`.
On my machine, this restores the attractors example to working state. Thanks @martinRenou for help debugging.
Fixes #52. Alternative to #81.
=> Fix attractors example

envisage/plugins/ipython_kernel/tests/test_internal_ipkernel.py, envisage/plugins/ipython_kernel/tests/test_ipython_kernel_plugin.py, etstool.py
- Include `ipykernel` in CI setup, so that the IPython-related tests are run as part of the CI (they're currently skipped).
- Rework the check in one of the test files so that we don't try to import `IPython`.
=> Add ipykernel package to CI setup

.travis.yml, appveyor.yml, setup.py
Now that Envisage 4.7.0 is released, we should bump the version number on master.
EDIT: Also updates the CI configs to build PRs against branches named "release/<nnn>.<nnn>.x".
=> Post-release version-number bump on master.

.travis.yml, appveyor.yml, setup.py
Bump version number in case we decide we want a 4.7.1 bugfix release.
EDIT: Also modifies the CI to do builds of PRs against branches named "release/<nnn>.<nnn>.x". These commits should also go into master.
=> Bump version number on release branch.

envisage/extension_point_binding.py
Fix a single use of the deprecated `HasTraits.set` method. This was causing `DeprecationWarning`s in the test suite of another project.
I did a quick search for other uses of `HasTraits.get` and `HasTraits.set`, but didn't spot any.
=> Replace use of deprecated HasTraits.set method with HasTraits.trait_set.

envisage/plugin.py, envisage/tests/plugin_test_case.py
Fixes #119
@mdickinson @rahulporuri I believe this solves the problem. `HasTraits` already has an internal method for inspecting its MRO for methods that avoids tripping the infinite recursion since it doesn't really touch the instance. Swapping that in for `inspect.getmembers()` solves the problem for me.
=> BUG: Fix infinite recursion in extension method harvesting.

envisage/plugins/ipython_kernel/internal_ipkernel.py, etstool.py
This is a proposed fix to get over the changes coming with ipykernel 4.7. The `kernel.io_loop` was not initialized as in 4.6 leading to a failure in our test suite because the initialization was not triggered and the cleanup code of IPython was expecting the `io_loop` to be present. 
The changes introduced in this PR should not cause any troubles as they initialize the io_loop but does not start it.
It should fix #107
=> fix broken tests with ipykernel 4.7

MANIFEST.in, setup.py
Fixes #106 by adding `LICENSE.txt`, `README.rst`, `CHANGES.txt` and related files to the manifest.
=> Include license, readme and changelog files in the source distribution.

envisage/developer/charm/charm.py, envisage/developer/ui/view/plugin_browser.py, envisage/ui/single_project/view/project_view.py
This PR was prompted by #65 and I made a few trivial fixes to imports and broken usage. See details for the full output when I ran `python setup.py test` from this branch.
<details>
```
running test
running egg_info
creating envisage.egg-info
writing envisage.egg-info/PKG-INFO
writing dependency_links to envisage.egg-info/dependency_links.txt
writing entry points to envisage.egg-info/entry_points.txt
writing requirements to envisage.egg-info/requires.txt
writing top-level names to envisage.egg-info/top_level.txt
writing manifest file 'envisage.egg-info/SOURCES.txt'
reading manifest file 'envisage.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'envisage.egg-info/SOURCES.txt'
running build_ext
/home/rporuri/.edm/envs/temp3/lib/python3.6/site-packages/IPyt …
```
=> Update (a few) broken imports and usage

envisage/ui/tasks/tasks_application.py
Moves the logic for deciding whether to restore from state or from the default layout out of the `create_window` arguments
=> Bugfix for issue #143

envisage/plugins/ipython_kernel/internal_ipkernel.py, envisage/plugins/ipython_kernel/tests/test_internal_ipkernel.py
The internal IPython kernel, at start time, replaces `sys.stdout` and `sys.stderr` with its own objects of type `OutStream`. This PR records the original values of `sys.stdout` and `sys.stderr` at kernel start time, and restores them when shutting down the kernel.
This fixes some causes of obscure "TypeError: heap argument must be a list" exceptions in envisage and projects using it: the replacement `sys.stdout` and `sys.stderr` objects had references to a shut-down tornado IO loop, and attempts to write to either of those streams after the IO loop had been shut down would fail.
=> InternalIPKernel: restore original streams at kernel shutdown time.

etstool.py
- Make `--toolkit` and `--runtime` options use `click.Choices`, to improve help and error reporting.
- Change default Python version to 3.6.
- Factor out repetition of defaults for the various tasks.
- Provide support for `--editable` model for the `install` and `update` commands.
- Replace uses of `python setup.py install` with `pip install .`
=> Minor improvements to etstool.py usability.

envisage/extension_point.py, envisage/tests/extension_point_test_case.py
The str repr should display the `id` attr of `ExtensionPoint` instances.
Fixes #141
=> String repr for ExtensionPoint objects

envisage/plugins/ipython_kernel/internal_ipkernel.py, envisage/plugins/ipython_kernel/tests/test_internal_ipkernel.py
The consoles created by `InternalIPKernel.new_qt_console` are `subprocess.Popen` instances created with `stderr=PIPE` and `stdout=PIPE`. We kill those subprocesses at shutdown time, but don't close the pipes. This leads to `ResourceWarning`s (at least in Python 3) from code using this.
This PR explicitly closes the pipes.
=> InternalIPKernel: fix ResourceWarnings from unclosed pipes.

.travis.yml, appveyor.yml, install-edm-windows.cmd
- Update to EDM 1.11.0
- Don't fail fast: we generally want all jobs to run, especially when messing with different GUI backends
- Run CI on PRs against any branch, not just against master or release branches.
=> Update EDM version and simplify Travis and Appveyor configurations

docs/source/envisage_core_documentation/howto_create_a_plugin.rst
* Add a missing right bracket to a typo
=> Add missing right bracket to tetris example

.travis.yml
This PR is an attempt to fix recently failing Travis CI cron jobs for this repository.
See https://docs.travis-ci.com/user/gui-and-headless-browsers/ for details on currently supported methods for launching xvfb.
See also the [blog post](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment) from Travis CI about the Xenial rollout.
Here's the tail of the log for a [recent failing run](https://travis-ci.org/enthought/envisage/jobs/544772333)
```
travis_fold:start:before_install.1
[0Ktravis_time:start:0b9aa365
[0K$ mkdir -p "${HOME}/.cache/download"
travis_time:end:0b9aa365:start=1560349798741229483,finish=1560349798745664143,duration=4434660
[0Ktravis_fold:end:before_install.1
[0Ktravis_fold:start:before_install.2
[0Ktravis_time:start:2ef9439a
[0K$ export …
```
=> Update .travis.yml for framebuffer-related changes

.travis.yml
Use of "sudo: false" is deprecated. Remove it from the Travis CI config.
ref: https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
=> Remove "sudo: false" from Travis CI config

.travis.yml, etstool.py
The changes introduced in this PR are based on similar changes in the PR https://github.com/enthought/traits/pull/479
Essentially, we do two things here
- update the `install` command to install certain packages from source, via the use of a `--source` command line flag
- update travis to use the `--source` flag when the event type is a cron job.
=> Test ETS packages from source using cron jobs 

envisage/extension_point.py
This PR removes some debugging code from the `ExtensionPoint` source: it's hard to imagine that it's particularly useful to have this one `etsdevtools` usage right here but not in any other failure paths. And it's not hard for a developer to insert an `import traceback; traceback.print_stack()` during debugging if they want equivalent functionality.
Together with #166, this removes all uses of the obsolescent (senescent?) `etsdevtools` package.
=> Remove debugging helper from ExtensionPoint source.

envisage/plugins/python_shell/view/namespace_view.py, envisage/ui/gui_application.py, envisage/ui/tasks/tasks_application.py, examples/plugins/single_project/sample_project/data/plugin/model_service.py, examples/plugins/tasks/ipython_kernel/example.py
Some low-hanging fruit in the current Sphinx autodoc warnings (from #165): remove (ab)uses of "Returns:" and "Parameters:" in the codebase.
=> NumpyDoc style fixes

examples/Hello_World/hello_world.py, examples/MOTD/acme/motd/motd_plugin.py, examples/MOTD_Using_Eggs/src/acme.motd/acme/motd/motd_plugin.py, examples/plugins/tasks/ipython_kernel/example.py
Fix some `print`-related SyntaxErrors on Python 3.
This leaves the codebase free of syntax errors for me: tested with `flake8 --select=E9`.
=> Fix syntax errors on Python 3.

docs/source/tasks_user_manual/extensibility.rst, envisage/ui/tasks/tasks_application.py
Fixes the comment for `TasksApplication.always_use_default_layout` to be consistent with the usage.
Also makes some grammar and spelling fixes in the corresponding documentation.
See also #143 and #144.
=> Fix confusing doc-comment for always_use_default_layout.

envisage/egg_basket_plugin_manager.py, envisage/egg_plugin_manager.py, envisage/plugin.py, envisage/provider_extension_registry.py, envisage/ui/action/action_set.py, envisage/ui/single_project/project.py, envisage/ui/tasks/tasks_application.py
Replace uses of the long-deprecated `Logger.warn` with `Logger.warning`.
=> Fix deprecation warnings from use of Logger.warn

envisage/ui/tasks/tasks_plugin.py
The [current documentation](https://docs.enthought.com/envisage/api/envisage.ui.tasks.html#envisage.ui.tasks.tasks_plugin.TasksPlugin) for the `TasksPlugin` doesn't show the extension points. This PR fixes that.
=> Add docstrings for tasks plugin extension points

envisage/plugins/ipython_kernel/internal_ipkernel.py, envisage/plugins/ipython_kernel/tests/test_internal_ipkernel.py
When starting, the IPython kernel prints the following message to the console:
```
NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.
To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.
To read more about this, see https://github.com/ipython/ipython/issues/2049
```
That message isn't particularly useful for our case of embedding an IPython prompt inside an application. This PR suppresses it.
=> Suppress the Ctrl-C message issued by the IPython kernel.

envisage/ui/tasks/tests/test_tasks_application.py
The drive-by-fix in #179 was broken: we want to actually *skip* the test if `ETS_TOOLKIT` is not defined.
=> Properly skip tests if ETS_TOOLKIT isn't defined.

setup.py
`setup.py` cleanup and changes in preparation for release
@rahulporuri : I've extended the install-from-archive logic a bit; could you take a look, and see what you think? It now allows installation from an archive for a non-released version, but instead of inventing a dev number it uses `"4.5.6.dev-unknown"` in that case. That's not PEP 440 compliant, so it'll force would-be uploaders to think before uploading, but the package will be otherwise functional.
Other highlights:
- add "six" and "setuptools" to dependencies
- don't leave a file unclosed when reading the long description
- change "author" field
- add missing "long_description_content_type" field (twine warns about this)
- refine and extend trove classifiers
- remove "platform" field, which is redundant with the classifiers
- …
=> More setup.py revisions

etstool.py
the changes are borrowed from https://github.com/enthought/traits/pull/512/
fixes #163
=> Update etstool to work with non-edm bootstrap env on win

setup.py
[PR against the newly-created `release/4.8.x` branch]
Set `IS_RELEASED` to `True` in preparation for 4.8.0 release.
=> Bump version information in preparation for 4.8.0 release.

README.rst
Drive-by consistency fix for the badges in the README. Probably doesn't fix issue #215.
- Use https consistently.
- Use SVG for both badges (instead of a mix of PNG and SVG)
- Add an `:alt:` for the coverage badge.
=> Consistency fixes for badges in README

envisage/resource/tests/test_resource_manager.py, envisage/tests/test_application.py, envisage/tests/test_class_load_hook.py, envisage/tests/test_composite_plugin_manager.py, envisage/tests/test_core_plugin.py, envisage/tests/test_egg_based.py, envisage/tests/test_egg_basket_plugin_manager.py, envisage/tests/test_egg_plugin_manager.py, envisage/tests/test_extension_point.py, envisage/tests/test_extension_point_binding.py, envisage/tests/test_extension_point_changed.py, envisage/tests/test_extension_registry.py, envisage/tests/test_import_manager.py, envisage/tests/test_package_plugin_manager.py, envisage/tests/test_plugin.py, envisage/tests/test_plugin_manager.py, envisage/tests/test_provider_extension_registry.py, envisage/tests/test_safeweakref.py, envisage/tests/test_service.py, envisage/tests/test_service_registry.py, envisage/tests/test_slice.py, envisage/ui/action/tests/test_action_manager_builder.py
- Fix DeprecationWarnings from `failUnlessRaises` and `assert_`
- Turn existing non-context-manager uses of `assertRaises` into the context manager form
- Remove some unnecessary boilerplate from test modules
Closes #207
=> Fix DeprecationWarnings, remove boilerplate.

etstool.py
Both #227 and #228 will require `mock` for testing on Python 2. This PR pulls out the necessary etstool.py changes.
=> Add mock to dependencies on Python 2.

envisage/plugins/ipython_kernel/kernelapp.py, envisage/plugins/ipython_kernel/tests/test_internal_ipkernel.py
If `IPython.utils.io.stdout` doesn't exist (which happened in practice in an application, and which could in theory happen in the future in upstream `IPython`), then `IPKernelApp` fails to start correctly. This PR fixes that, and makes sure that the original state is restored in all cases.
Fixes #218.
=> Correctly restore IPython.utils.io.stdout state in all cases

envisage/plugins/ipython_kernel/kernelapp.py, envisage/plugins/ipython_kernel/tests/test_internal_ipkernel.py
=> Add a test to check that the InternalIPKernel doesn't affect sys.path.

.travis.yml, appveyor.yml, install-edm-linux.sh, install-edm-osx.sh, install-edm-windows.cmd
This PR prempts CI failures seen on other ETS packages related to invalid metadata found in new eggs. 
NOTE : Ensure that we install the cli installer and not the full edm installer - which is very large in size and install the GUI which is not needed on the CI machines.
See similar PR in traits here - https://github.com/enthought/traits/pull/560
=> Update edm version and config/install scripts

CHANGES.rst, MANIFEST.in
The changelog (which is formatted as reStructuredText) renders more nicely in GitHub if we give it the correct extension. (And we may even want to include it in the generated documentation some day.)
=> Fix extension on the reStructuredText-formatted changelog.

CHANGES.rst, envisage/tests/test_egg_basket_plugin_manager.py
With this change, the test run output is clean for me.
=> Remove a use of 'print' in the test suite.

envisage/plugins/python_shell/view/python_shell_view.py
Replace a use of the Traits convenience trait type `DictStrAny` with `Dict(Str, Any)`.
=> Replace use of DictStrAny with Dict(Str, Any)

envisage/ui/single_project/project.py, envisage/ui/single_project/tests/test_clean_strings.py
This PR copies the `clean_filename()` utility function from the `Traits` codebase into Envisage, as it is currently used in the `SingleProject` code and slated to be removed from Traits. Additionally, the test suite from Traits for this function is copied into the `SingleProject` tests.
IIUC, this should finish the work for #245
=> MAINT: copy clean_filename from Traits

envisage/plugin.py
`AdaptedTo` is deprecated. `Supports` is an exact synonym.
See enthought/traits#723.
=> Replace a comment mention of AdaptedTo with Supports

setup.py
This PR, against the 4.9.x release branch, bumps the version in preparation for the 4.9.1 bugfix release.
Note: do not merge until after merging #258
=> Bump the version for the 4.9.1 release.

CHANGES.rst, envisage/tests/test_core_plugin.py, setup.py
The test suite for Envisage 4.9.1 fails against the latest release of Traits (Traits 6.0.0), due to the removal of Traits categories. (Envisage master no longer depends on Traits categories; so this is only an issue in this release series.)
This PR "fixes" the issue by skipping the relevant tests if Traits categories are not available.
Also bumps the version number and updates the changelog in preparation for a 4.9.2 release.
=> Make 4.9.2 release containing fix for tests that depend on Categories

docs/source/tasks_user_manual/extensibility.rst, envisage/ui/tasks/action/task_window_toggle_group.py, envisage/ui/tasks/preferences_category.py, envisage/ui/tasks/preferences_dialog.py, envisage/ui/tasks/task_factory.py, envisage/ui/tasks/tasks_application.py, examples/plugins/tasks/attractors/attractors_preferences.py, examples/plugins/tasks/attractors/model/henon.py, examples/plugins/tasks/attractors/model/i_model_2d.py, examples/plugins/tasks/attractors/model/i_model_3d.py, examples/plugins/tasks/attractors/model/i_plottable_2d.py, examples/plugins/tasks/attractors/model/lorenz.py, examples/plugins/tasks/attractors/model/rossler.py, examples/plugins/tasks/attractors/model_help_pane.py, examples/plugins/tasks/attractors/plot_2d_pane.py, examples/plugins/tasks/attractors/plot_3d_pane.py, examples/plugins/tasks/ipython_kernel/i_python_editor.py, examples/plugins/tasks/ipython_kernel/python_editor.py, setup.py
More Python 2 / Python 3 cleanup: replace uses of the `Unicode` trait with `Str`.
=> Replace uses of the semi-deprecated Unicode with Str

envisage/ui/workbench/workbench_application.py
There's a heavily commented `import traitsui` in `workbench_application.py`. The comments state that `traitsui` must be imported before other parts of ETS, but don't give any indication why.
Moreover, since `import traitsui` is close to a no-op (all the fun side-effects and content come from `traitsui.api`), it's difficult to see how those comments could be true.
This PR removes the import and rationale.
=> Remove an unused import and bogus rationale for that import

envisage/tests/test_slice.py
Fix E741 complaints from flake8.
I'm in two minds about this one: I don't think I've ever been confused by use of `l` as a variable name, but I can see how it might depend on working environment. So let's fix it.
=> Fix complaints about 'l' as an identifier

envisage/tests/test_class_load_hook.py, envisage/tests/test_composite_plugin_manager.py, envisage/tests/test_core_plugin.py, envisage/tests/test_egg_based.py, envisage/tests/test_egg_basket_plugin_manager.py, envisage/tests/test_egg_plugin_manager.py, envisage/tests/test_extension_point.py, envisage/tests/test_extension_point_binding.py, envisage/tests/test_extension_point_changed.py, envisage/tests/test_extension_registry.py, envisage/tests/test_import_manager.py, envisage/tests/test_package_plugin_manager.py, envisage/tests/test_plugin.py, envisage/tests/test_plugin_manager.py, envisage/tests/test_safeweakref.py, envisage/tests/test_service.py, envisage/tests/test_service_registry.py, envisage/tests/test_slice.py, envisage/ui/action/tests/dummy_action_manager_builder.py, envisage/ui/action/tests/test_action_manager_builder.py
The `unittest_tools` imports dated from the days of Python 2.6 support, which was dropped long ago: they were needed for various `TestCase` features that were only added in Python 2.7.
This PR removes them.
=> Import unittest directly instead of from unittest_tools

envisage/extension_registry.py, envisage/safeweakref.py, envisage/tests/test_extension_registry.py, envisage/tests/test_safeweakref.py, setup.cfg
Some `safeweakref`-related cleanup, aimed at eventual removal of the `safeweakref` module.
- Don't try to make `safeweakref` a drop-in replacement for `weakref`: `safeweakref` no longer does `from weakref import *`
- Deprecate the existing `safeweakref.ref`
- Replace existing uses of `safeweakref` with a simpler, private version that still handles bound methods specially, but doesn't do the caching that `safeweakref` does
- Add tests for the deprecation of `safeweakref.ref`
- Add tests to cover the uses of that simpler replacement.
- Make `safeweakref` flake8-clean, and remove it from the flake8 exclusion list.
Closes #271
=> Deprecate safeweakref and replace its uses

.travis.yml
This PR adds Slack notification to the Enthought internal #ets-bots Slack channel.
cf. enthought/traits#1074
=> Add Slack notification for Travis CI runs

.travis.yml, appveyor.yml, etstool.py
This PR removes CI builds for Python 3.5.
Note: Python 3.5 is still supported, but our build machinery depends on EDM, and we no longer build packages for EDM on Python 3.5, so the latest packages are only available for 3.6.
cf. enthought/traits#1044
=> Don't build CI on Python 3.5

.travis.yml, appveyor.yml, etstool.py
Update the CI builds and etstool.py
- Don't support PyQt4 and PySide; only PyQt5 and PySide2
- Remove CI tests for PyQt4
- Add CI tests for PyQt5 (from EDM) and PySide2 (from pip)
xref: https://github.com/enthought/pyface/pull/512/files
=> Remove support for PySide and PyQt4 from CI

.travis.yml, appveyor.yml
This PR fixes independent CI failures on Linux and Windows
- On Windows, force use of VS 2019, to avoid a test hang due to a bluetooth-related popup from PyQt5.
- On Linux, make sure necessary libxcb-* packages are installed.
~The continuous integration is unhappy again on Linux. This is a debugging PR intended to help track down what's wrong.~
=> Fix CI failures on Linux, Windows

.travis.yml, appveyor.yml
This PR removes the code coverage reporting; the generated reports weren't useful, and were just extra noise in the GitHub notifications.
Related: enthought/traits#1109
=> Don't report code coverage

.travis.yml, appveyor.yml
3.0.1 is the latest version of edm. Note that on edm 3.0.1, the platform used on linux is `rh7-x86_64`, not `rh6-x86_64`. fixes #294
=> Use edm 3.0.1 instead of 2.0.0

envisage/ui/tasks/tasks_application.py, envisage/ui/tasks/tests/test_tasks_application.py
Note that this is already how the `GUIApplication` behaves. I'm not sure why the `TasksApplication` behaved differently earlier. https://github.com/enthought/envisage/blob/8eddfc402f2be38bf8774e48ab31a118d8dcb565/envisage/ui/gui_application.py#L43-L44
=> Make TasksApplication.gui expect an IGUI interface, not a GUI instance

etstool.py
This PR adds a new `shell` click command - which when run activates the development environment for traits. The usual command line options are available to choose the environment name and the runtime version/toolkit of the development environment. Underneath the hood, the click command just uses the `edm shell` command with the appropriate environment name, which is why the docstring for the click command is _almost_ the same as that of `edm shell`.
=> Add a new shell click command

envisage/plugins/event_manager/api.py, envisage/plugins/ipython_kernel/tests/test_internal_ipkernel.py, envisage/plugins/ipython_kernel/tests/test_ipython_kernel_plugin.py, envisage/tests/test_ids.py, examples/plugins/tasks/ipython_kernel/example.py
fixes #306 
This PR creates a new `envisage.plugins.event_manager.api` module and populates it with the relevant plugin class.  It also adds to the existing `envisage.plugins.ipython_kernel.api` module to import all the classes listed in the issue 306 description.  Finally, it imports from the api module in tests/examples.
=> create and fill plugin subpackage api modules

examples/Hello_World/hello_world.py
The fix is fairly trivial - it is replacing `logging.StreamHandler` with `logging.FileHandler`.
=> Fix the Hello_World example

examples/plugins/tasks/attractors/README.txt, examples/plugins/tasks/attractors/attractors_application.py, examples/plugins/tasks/attractors/attractors_plugin.py, examples/plugins/tasks/attractors/model/henon.py, examples/plugins/tasks/attractors/model/i_plottable_2d.py, examples/plugins/tasks/attractors/model/lorenz.py, examples/plugins/tasks/attractors/model/rossler.py, examples/plugins/tasks/attractors/plot_2d_pane.py, examples/plugins/tasks/attractors/plot_3d_pane.py, examples/plugins/tasks/attractors/run.py, examples/plugins/tasks/attractors/visualize_2d_task.py, examples/plugins/tasks/attractors/visualize_3d_task.py, examples/plugins/tasks/index.rst
The fixes are mostly trivial - involving updating implicit imports to explicit imports.
To be able to run this example, you will need to install `numpy`, `scipy`, `mayavi` and `chaco` in the envisage devenv and then do `python -m attractors.run` from the `examples/plugins/tasks` directory.
=> Fix the attractors tasks application example

examples/MOTD/acme/motd/api.py, examples/MOTD/acme/motd/message.py, examples/MOTD/acme/motd/motd.py, examples/MOTD/acme/motd/motd_plugin.py, examples/MOTD/acme/motd/software_quotes/software_quotes_plugin.py, examples/MOTD/run.py
The fixes were mostly trivial - using `logging.FileHandler` instead of `logging.StreamHandler` and using explicit imports instead of implicit imports.
=> Fix the MOTD example

README.rst, setup.py
fixes #126 
This PR adds `extras_require` to `setup.py` and also updates the readme to mention the optional dependencies.
The issue originally mentioned `tornado` but I am not sure this is still really needed?  `tornado` is listed as a required dependency of `ipykernel` and the only occurrences of "tornado" in envisage are:
https://github.com/enthought/envisage/blob/8eddfc402f2be38bf8774e48ab31a118d8dcb565/envisage/plugins/ipython_kernel/kernelapp.py#L76-L94
https://github.com/enthought/envisage/blob/1eccd8074c1bc0661b64fba287cc88add446ada4/envisage/plugins/ipython_kernel/tests/test_internal_ipkernel.py#L29-L35
and
https://github.com/enthought/envisage/blob/1eccd8074c1bc0661b64fba287cc88add446ada4/envisage/plugins/ipython_kernel/tests/test_internal_ipkernel.py#L242-L244
It also may be …
=> Document extra dependencies

envisage/api.py, envisage/core_plugin.py, envisage/plugins/ipython_kernel/tests/test_ipython_kernel_plugin.py, envisage/tests/test_core_plugin.py, envisage/tests/test_ids.py, examples/MOTD/run.py, examples/plugins/tasks/attractors/run.py, examples/plugins/tasks/ipython_kernel/example.py, examples/plugins/workbench/AcmeLab/run.py, examples/plugins/workbench/Lorenz/run.py
fixes #308 
The issue was originally framed as a question, but this PR assumes that re-exporting `CorePlugin` via `envisage.api` is the correct solution.  (Maybe instead it should be moved to `envisage/plugins/core/core_plugin.py` and be placed in an `envisage.plugins.core.api` module? but since it is `core` that probably is not the right approach and I think including it in `envisage.api`, as is done in this PR, makes more sense.
This PR simply re-exports `CorePlugin` in `envisage.api`, adjusts `core_plugin.py` to not import from `envisage.api` to avoid circular imports, and has tests/examples import `CorePlugin` from the api now instead.
=> Re-export CorePlugin in envisage.api

envisage/extension_point.py, envisage/plugin.py, envisage/service.py, envisage/tests/test_extension_point.py, envisage/tests/test_plugin.py, envisage/tests/test_service.py
fixes #208 
This PR follows the lead of #142 by making the reprs for `Plugin` and `Service` be
`"Plugin(id={!r}, name={!r})".format(self.id, self.name)` and `"Service(protocol={!r})".format(self._protocol)` respectively.  It also adds simple tests to verify these work as expected.  It is very possible that something other than `self.id` and `self.name` for `Plugin` and `self._protocol` for `Service` may be more meaningful / useful for debugging envisage applications.  If a reviewer finds that to be the case I am happy to modify.
Also, the `Service` repr is a little ugly now (although more informative) as it uses the repr of the protocol inside its own repr.  Especially in cases where protocol has a noisy/long repr.  For example in the test case added this becomes `Service(protocol=<class …
=> Add more meaningful reprs for Plugin / Service classes

.travis.yml, appveyor.yml, etstool.py
fixes #312 
Note that previously, "wx" was listed in `available_toolkits`, but not in `supported_combinations` so trying to run `python etstool.py install --toolkit=wx` resulted in a failure.  Additionally, wx had been completely removed from CI altogether. (see #225)
This PR updates `etstool.py` so that wx is included in `supported_combinations` so that one can actually install and run tests with wx as the toolkit.  It also re-adds wx a as a toolkit to be run in CI.  Also, to address the original issue, it installs the relevant version of wx by following what is done in traitsui:
https://github.com/enthought/traitsui/blob/d112a694a4d681861a7ad3abb513cf7c83da9fe5/etstool.py#L246-L255
If we wish to continue simply not having wx as an available toolkit, we can close this PR.  If we do that …
=> Add wx as being supported in etstool, add it back to CI, and test against wxPython v4.x 

envisage/tests/test_extension_registry.py, envisage/tests/test_extension_registry_mixin.py, envisage/tests/test_provider_extension_registry.py
fixes #281
This PR pulls out methods from `test_extension_registry.ExtensionRegistryTestCase` into a mixin class called `test_extension_registry_mixin.ExtensionRegistryTestMixin` which both `ExtensionRegistryTestCase` and `ProviderExtensionRegistryTestCase` now inherit from.  
Test methods which were previously in `ExtensionRegistryTestCase` and overridden in `ProviderExtensionRegistryTestCase` have been left in these respective test cases and not included in the mixin.
This should make it easier to add new tests to `ExtensionRegistryTestCase`.
I searched for other TestCase subclassing but the only other occurrence I found was `EggBasedTestCase` being subclassed by `test_egg_plugin_manager.EggPluginManagerTestCase`.  This I felt was fine to leave though because `EggBasedTestCase` actually …
=> Use mixin instead of having ProviderExtensionRegistryTestCase inherit from ExtensionRegistryTestCase

docs/source/conf.py, docs/source/envisage_core_documentation/introduction.rst, docs/source/envisage_core_documentation/services.rst
This is a trivial PR that simply fixes a couple of typos I noticed reading the docs, and updates the copyright date shown on the docs from 2019 to 2020
=> Doc - fix a few typos and old copyright year

docs/source/conf.py
fixes #342 
This PR adds the intersphinx extension to the list of extensions - and adds the traits, tratsui and pyface docs urls to intersphinx. This enables links to api docs from the respective dependencies for example from the envisage api docs.
=> Setup intersphinx in docs

CHANGES.rst, README.rst, setup.py
fixes #313 
This PR simply updates the `setup.py` script in two places and adds a short message to `CHANGES.txt` mentioning support for python <= 3.5 is dropped
=> drop support for python 3.5

envisage/core_plugin.py, envisage/plugin.py, envisage/tests/test_core_plugin.py
fixes #251 
This PR first adds a failing regression test for the error described in the issue.  
To fix the issue, I added a listener in the `CorePlugin` class that listens to the `service_registry`'s `unregistered` event trait.  As mentioned in the issue, when `Application.unregister_service(<id>)` was called, the id was not also removed from `CorePlugin._service_ids`, so in the handler we simply remove the unregistered service id from `self._service_ids`.
=> Fix Unregister service value error bug

etstool.py
In #162 cron jobs were set up and the framework was added so that they could installed ets packages from source.  `apptools` was not included originally in the list of `source_dependencies`, but it should be.
=> Add apptools to source_dependencies in etstool.py

envisage/tests/test_extension_point.py, envisage/tests/test_extension_point_changed.py
This PR add tests to demonstrate the contradiction / challenge for solving #291.
In summary:
- `ExtensionPoint` is like a property. Its value is recomputed on every access of the attribute.
- Mutating the extension point list _directly_ has no effects on the registry, nor will it fire events for the `x_items` listener
- Being able to listen to `x_items` is misleading. 
Details:
When someone defines an ExtensionPoint in their class like this:
```
class MyApplication(Application):
x = ExtensionPoint(List, id="my.extension")
```
One can listen to changes to `x_items`, like this:
```
@on_trait_change("x_items")
def handle(self):
....
```
This makes developers believe that `x` is like a persisted list and they can listen to its mutation.
But that is in fact not true. The value of the extension …
=> Add tests to demonstrate behaviour when mutating extension point directly

envisage/extension_point_changed_event.py, envisage/tests/test_extension_point_changed.py
fixes #352 
This PR simply overrides the repr method of `ExtensionPointChangedEvent` so that printing an instance of `ExtensionPointChangedEvent` will not result in something like
`TraitListEvent(index=None, removed=[], added=[42, 'a string', True])`. 
The new repr is very similar, only changing `TraitListEvent` to `ExtensionPointChangedEvent` and mentioning the `extension_point_id` of the `ExtensionPointChangedEvent`.
=> Add a specific repr for ExtensionPointChangedEvent

envisage/tests/test_extension_registry_mixin.py
In #347, I added more tests for the ExtensionRegistry. This PR brings two of the tests to master.
`test_get_extensions_mutation_no_effect_if_undefined`: Ensures mutating the list returned by `get_extensions` has no effect on the registry. This is the only test that fails if I remove the `[:]` in this line:
https://github.com/enthought/envisage/blob/0798c1c6ce29628f4ef7221c564f5efc81709c78/envisage/extension_registry.py#L114
`test_get_extension_point_return_none_if_not_found` tests the leniency of `ExtensionRegistry.get_extension_point` when the id is not defined. Attempt to break this test also breaks some other indirect tests to do with the removing extension points via `ProviderExtensionRegistry`, which subclasses `ExtensionRegistry`. I feel a more directed test is needed for this …
=> Add tests for ExtensionRegistry getters

CHANGES.rst
As mentioned here: https://github.com/enthought/envisage/pull/364#discussion_r528879640
This portion of the changelog can be updated independently of the content for the 5.0.0 release.  This PR simply adds a small section to the changelog detailing the 4.9.2 bugfix release.
=> update changelog to mention 4.9.2 bugfix release

envisage/plugin.py, envisage/tests/test_extension_point_changed.py
When the extensions list is changed by adding or removing a plugin, the ExtensionPointChangedEvent reports a slice object as the index, but the end value is incorrect: If one uses that index to reproduce the new list from the values of the old list, they get incorrect results.
The first commit adds two assertions. The first assertion fails with master like this:
```
Traceback (most recent call last):
File "/Users/kchoi/Work/ETS/envisage/envisage/tests/test_extension_point_changed.py", line 268, in test_assign_non_empty_list
listener.new.removed, source_values[listener.new.index]
AssertionError: [1, 2, 3] != [1, 2, 3, 98]
```
That is, if you use the index on the old values to recover the removed values, you get the wrong answer.
The second assertion fails with master like this:
``` …
```
=> Fix index slice in ExtensionPointChangedEvent when plugin changes

CHANGES.rst
This PR simply updates the changelog with the PRs since the last release.  It also adds a section to the changelog for the last release of 4.9.2 which was a small bug fix release.  
In order for this to match the process that was done for https://github.com/enthought/traitsui/issues/1307, this PR should instead target a yet to be created `maint/5.0.0` branch instead of master.
=> Update changelog for 5.0.0 release

.github/ISSUE_TEMPLATE/release_template.md
This PR simply changes the name of the release issue template to "Release Checklist".  This is what you currently see when opening a new issue:
"Tracking Issue" is a bad name that doesn't make sense.
=> update name of release issue template

.github/ISSUE_TEMPLATE/release_template.md
This PR simply tries to clean up some markdown issues in the newly added release checklist issue template.
motivated by this comment: https://github.com/enthought/envisage/pull/371#issuecomment-733540297
=> Cleanup Release Issue Template

.travis.yml
This PR turns off expensive macOS builds on Travis CI. We'll eventually use GitHub Actions to replace these.
=> Turn off macOS builds on Travis CI

docs/source/conf.py, docs/source/envisage_core_documentation/extension_points.rst, docs/source/envisage_core_documentation/introduction.rst, docs/source/envisage_core_documentation/message_of_the_day.rst, docs/source/envisage_core_documentation/message_of_the_day_(using_eggs).rst, docs/source/envisage_core_documentation/plugins.rst, docs/source/envisage_core_documentation/services.rst, docs/source/envisage_core_documentation/workbench.rst, docs/source/tasks_user_manual/extensibility.rst, docs/source/tasks_user_manual/layout.rst, docs/source/tasks_user_manual/menus.rst
The documentation has URL links to sources on GitHub. Some of them can be replaced by cross references to the API documentation. Some of them cannot.
When we need to move files across (e.g. for solving #320, see #359), we would have to update these links laboriously. This PR refactors the links so that "https://github.com/enthought/envisage/tree/master/..." is only defined once, in `conf.py`. And when we do move the example files, only the link in `conf.py` requires changes.
There are some drive-by to replace GitHub links with API documentation references, as well as removing some dead links.
=> Refactor documentation links to source on GitHub

setup.py
[targeting maint/5.0.0]
This PR bumps the release version and flips the IS_RELEASE flag for the development of the next bug fix release.
=> Bump release version for the development of 5.0.1

CHANGES.rst
This PR simply updates the changelog to match the updates that were made on `maint/5.0.0`.
It also adds the release date, which did not get updated previously.
=> Update changelog after release of 5.0.0

envisage/ui/tasks/tasks_application.py, envisage/ui/tasks/tests/test_tasks_application.py
This PR simply change the default value for `layout_save_protocol` to 4 as protocol version 4 is safe for python >= 3.4.  It also removes a test that was testing that protocol 2 was used by default, which we no longer want.
This was missed when addressing #313
=> Change default pickle protocol to more recent version for python >= 3.4

envisage/examples/demo/plugins/tasks/attractors/model/henon.py, envisage/examples/demo/plugins/tasks/attractors/model/i_model_3d.py, envisage/examples/demo/plugins/tasks/attractors/model/lorenz.py, envisage/examples/demo/plugins/tasks/attractors/model/rossler.py, envisage/examples/demo/plugins/tasks/attractors/model_help_pane.py, envisage/examples/demo/plugins/tasks/attractors/plot_2d_pane.py, envisage/plugins/python_shell/view/namespace_view.py, envisage/ui/tasks/action/task_window_toggle_group.py, envisage/ui/tasks/task_window.py, examples/legacy/plugins/tasks/ipython_kernel/example_task.py, examples/legacy/plugins/tasks/ipython_kernel/python_editor.py
This PR replaces the `depends_on` in `Property` traits with `observe` instead. I tested that the attractors example still works as expected.
=> Replace "depends_on" in "Property" traits with "observe"

envisage/service_offer.py
This PR replaces the `Either` trait with the `Union` trait.
> A new Union trait type has been added. This is intended as a simpler replacement for the existing Either trait type, which will eventually be deprecated.
See https://github.com/enthought/traits/releases/tag/6.1.0.
See similar PR in traitsui https://github.com/enthought/traitsui/pull/1581
=> Replace "Either" trait type with "Union"

envisage/api.py, envisage/extension_point.py, envisage/plugin.py, envisage/tests/test_plugin.py
This PR removes the `contributes_to` decorator and the supporting code and tests.
This PR also stops checking for contributions to extension points in the `f"enthought.{extension_point_id}"` namespace.
fixes #399 and #398
=> Remove "contributes_to" decorator and supporting code

setup.py
After the recent traitsUI fiasco, this was on my mind.
After #400 we now depend on traits 6.2+
=> Explicitly require traits 6.2

setup.py
Simply update the `MICRO` version in the setup file and flip back `IS_RELEASED` to `False`.
=> Prepare 6.0 maintenance branch for 6.0.1 bugfix release

envisage/examples/demo/plugins/tasks/attractors/model/henon.py, envisage/examples/demo/plugins/tasks/attractors/model/lorenz.py, envisage/examples/demo/plugins/tasks/attractors/model/rossler.py
~fixes~ starts process of fixing #404
Previously changing `initial_point` at all one got the traceback:
```
Exception occurred in traits notification handler for event object: TraitChangeEvent(object=<attractors.model.henon.Henon object at 0x7fcc0ae66e60>, name='initial_point', old=array([0.1, 0.1]), new=array(['0.13', '0.1'], dtype='<U4'))
Traceback (most recent call last):
File "/Users/aayres/.edm/envs/envisage-test-3.6-pyqt5/lib/python3.6/site-packages/traits/observation/_trait_event_notifier.py", line 122, in __call__
self.dispatcher(handler, event)
File "/Users/aayres/.edm/envs/envisage-test-3.6-pyqt5/lib/python3.6/site-packages/traits/observation/observe.py", line 26, in dispatch_same
handler(event)
File "/Users/aayres/.edm/envs/envisage-test-3.6-pyqt5/lib/python3.6/site-packages/tra …
```
=> Start to fix Attractors example

envisage/extension_point.py, envisage/tests/test_extension_point.py, envisage/tests/test_extension_point_changed.py, envisage/tests/test_plugin.py
This PR reverts PR #354 from the `master` branch. This PR seems to be the cause of the issue #417 which is why we are reverting it, until we can investigate the issue and find a solution.
This PR also undoes a change to the plugin test case made in PR #401. Because we cannot use `observe` to listen to changes in an extension point anymore, the conversion from `_*_changed` to `observe` needed to be undone.
This PR replaces #418 which only tries to revert PR #354 on the maintenance branch. We prefer this PR over #418 because we don't want the `master` branch to be in a broken state.
=> Revert PR #354

envisage/tests/test_application.py
This PR adds a regression test for the issue described in #417 (where extension point contributions were being resolved before plugins had started).
The new test should fail on master, but pass once #417 is solved.
=> Regression test for #417

envisage/tests/test_ids.py
This PR skips an IPython-using test if IPython is not installed in the test environment.
Fixes #420.
@aaronayres35 @rahulporuri Do you think it would be possible to backport this for the 6.0.1 release?
=> Fix test suite dependence on ipykernel

CHANGES.rst, envisage/extension_point.py, envisage/tests/test_application.py, envisage/tests/test_extension_point.py, envisage/tests/test_extension_point_changed.py, envisage/tests/test_ids.py, envisage/tests/test_plugin.py
This PR backports the following PRs back to the `maint/6.0` branch in preparation for the 6.0.1 release - #421 , #422 and #423 . #422 reverted the original PR that is the cause of #417 , #421 adds a regression test for #417 and #423 ensures that the testsuite passes cleanly with minimal dependencies.
This PR also updates the changelog in preparation for the upcoming release.  Once this PR is merged, we will be in a place to make the 6.0.1 release.
=> Backport PRs #421, #422 and #423

setup.py
This PR simply flips `IS_RELEASED` from `False` to `True`, thereby making the 6.0.1 Envisage Release. The squash-merged commit on the `maint/6.0` branch will be tagged as the release commit.
=> Release Envisage 6.0.1

setup.py
We go from released 6.0.1 to in development 6.0.2.
=> Bump bugfix version number on 6.0 maintenance branch

etstool.py
Follow up to #426, see comment: https://github.com/enthought/envisage/pull/426#pullrequestreview-690385930
These changes should no longer be needed as we don't mess with the edm root directory anymore on the gh action workflows.
=> Revert recent changes to flake8 command in etstool.py

.github/workflows/ets-from-source.yml, .github/workflows/test-wx.yml
This PR sets up slack notification for the cron jobs. I manually triggered the cron jobs on this branch to ensure that the slack notifications get fired. Ref https://github.com/enthought/envisage/actions/runs/1027278891 and https://github.com/enthought/envisage/actions/runs/1027279665
One more step towards https://github.com/enthought/ets/issues/65
=> Setup slack notification for cron jobs

docs/source/envisage_core_documentation/services.rst
Change "minimimize" to "minimize" in two places.
=> Fix typo in services documentation

envisage/egg_plugin_manager.py, envisage/tests/test_egg_plugin_manager.py
The `EggPluginManager` uses the following trait definition for its working set:
```
working_set = Instance(pkg_resources.WorkingSet, pkg_resources.working_set)
```
This means that we're capturing the value of `pkg_resources.working_set` at import time, and using that value as the default for each `EggPluginManager`.
For testing purposes, it's convenient to be able to use a temporary replacement working set for `pkg_resources.working_set` to avoid test interactions. But this currently doesn't work.
This PR changes the `working_set` trait so that it looks up `pkg_resources.working_set` on first use, on a per-`EggPluginManager`-instance basis, instead of doing that lookup just once at import time.
=> Fix EggPluginManager to use current pkg_resources.working_set

envisage/tests/test_egg_basket_plugin_manager.py
Fix a test that was only passing as a result of side-effects from other tests in the same `TestCase`.
The test was passing when run as part of the complete test case because a distribution of `acme.foo` with version `0.1a1` was already in the global working set. This PR changes the test to explicitly add `acme.foo` to the global working set, so that the test passes both standalone and as part of the whole test case.
(Note that the global working set is reset at `tearDown` time, though I plan another PR to clean up the test side-effects.)
Closes #441
=> Fix a test that only passed due to test interactions

.github/ISSUE_TEMPLATE/release_template.md, README.rst, docs/source/conf.py, etstool.py
This PR replaces the use of `master` in the repo with `main` as the default branch name as been updated.
=>  Default branch has been renamed from "master" to "main"

docs/source/conf.py
At the moment, the documentation links to examples on the `main`/default branch. This isn't right because the examples might change in between releases, potentially confusing users who are referring to the documentation. This PR fixes that problem by making the documentation use version-specific links i.e. for the 6.0.1 release, the `6.0.1` tag will be used instead of the `main` branch.
I tested this locally by checking the links generated in the built docs - the examples links will be broken as expected as the dev version has no corresponding tag on GitHub. I then hardcoded the version in the sphinx configuration to `6.0.1` and the links worked as expected, pointing to the `6.0.1` tree instead of `main`.
=>  Don't link to examples on the main branch in documentation

.github/workflows/ets-from-source.yml, .github/workflows/test-with-edm.yml
The cron job recently started hanging for builds on PySide2 / macOS; this seems likely to be related to the GitHub Actions move to macOS 11 for its workers.
This PR contains a probable fix for the issue. Note that the `test-with-pypi.yml` workflow has _not_ been updated: our hypothesis is that it's only EDM builds of PySide2 that are affected.
(see also enthought/pyface#1056)
xref: https://github.com/enthought/envisage/runs/4558034418?check_suite_focus=true
=> Fix test hangs with PySide2 / macOS 11

envisage/import_manager.py
Simple drive-by modernization as I was reading code.  Should have no effective change in behaviour.
I can't remove the other __import__ usage easily however as it is doing a `from ... import ...`-style import.
=> Simplify ImportManager by using importlib

envisage/resource/package_resource_protocol.py, envisage/resource/tests/test_resource_manager.py, setup.py
Use `importlib.resources` in `PackageResourceProtocol` instead of `pkg_resources`.  Revised code should be completely compatible: `file` returns a byte stream, just as the `pkg_resources`-based code did.  Modernized error handling based on what `importlib.resources` raises for the cases we are interested in.
Also updated tests to use `importlib.resources`, and expanded their scope to catch some other cases of note.
There are other uses of `pkg_resources` in the codebase which are out of scope for this PR.
=> Update package resource protocol to use importlib.resources

envisage/plugins/ipython_kernel/tests/test_internal_ipkernel.py
This PR adds a workaround for test failures due to a bug(?) with `functools.lru_cache` on Python 3.6.
Closes #469
=> Add workaround for isinstance failure on Python 3.6

.github/workflows/ets-from-source.yml, .github/workflows/test-wx.yml
This PR updates the scheduled workflows to report failures to the main ETS channel rather than the more noisy bots channel, in the hope that they're more likely to be noticed there. Successes continue to be reported to the bots channel.
=> Report cron job failures to main Slack channel, not bots channel

docs/source/conf.py, etstool.py, setup.py
This PR does the following: 
- Use the `sphinx_copybutton` extension when building the Sphinx documentation
- Make `sphinx-copybutton` a `docs` extra for the `envisage` package
- Add a `pypi_dependencies` section to the `etstool` utility and add `sphinx-copybutton` as a PyPI dependency for the moment.
Ref https://sphinx-copybutton.readthedocs.io/en/latest/
=> Use the "sphinx-copybutton" extension in documentation

CHANGES.rst
This PR updates the changelog in preparation for the 6.1.0 release of Envisage.
Note: it also adds the changelog for the 6.0.1 release, which was missing from this branch (though present in the release branch).
=> Update changelog in preparation for the 6.1.0 release

setup.py
This PR bumps the version on the maintenance branch for continued development towards Envisage 6.1.1 (should that prove necessary).
=> Bump version number for continued development towards Envisage 6.1.1

setup.py
CI is currently failing thanks to a backwards incompatible change in PySide6 6.4.0, which affects Pyface. We'll pin the PySide6 version until Pyface has a chance to adapt to the PySide6 changes.
Fixes #486.
=> Pin PySide6 version

envisage/ui/tasks/tasks_application.py, envisage/ui/tasks/tests/test_tasks_application.py
Inspired by discussion in #489, where @corranwebster observes that:
> But there is something a bit dodgy about _initialize_application_home in that it isn't using self.state_location but a hard-coded path instead: if state_location changes after __init__ then you'll end up with this situation.
And indeed `_initialize_application_home` should depend on `self.state_location` as the single point of truth for the location; the current code will create the wrong directory in the event that the user passed `state_location` when creating the application.
This PR fixes that, and adds a regression test.
=> Use the correct state location when creating the folder

.github/workflows/ets-from-source.yml, .github/workflows/test-with-edm.yml, .github/workflows/test-wx.yml, etstool.py
This PR fixes the wxPython workflow:
- Use ubuntu-latest instead of ubuntu-20.04 (this also fixes that we were testing for ubuntu-latest when deciding whether to use xvfb-run or not)
- Add libnotify.so.4 as a wxPython dependency
- Use the ubuntu-22.04 wheel for wxPython
It also updates the `action/cache` version, in response to warnings.
Test run: https://github.com/enthought/envisage/actions/runs/3854233633
=> Switch to ubuntu-22.04 for wxpython run

envisage/tests/test_egg_based.py
1) Use sys.executable instead of 'python' to generate eggs to ensure the eggs are generated for the currently running python version.
2) Ensure the egg generation is run with a clean environment (stray environment variables caused problems on Debian, for instance).
=> Make test egg generation more reliable

CHANGES.rst
This PR brings in changelog updates from the recent 6.1.1 Envisage release.
=> Add 6.1.1 changes to changelog

envisage/ui/tasks/tasks_application.py, envisage/ui/tasks/tests/test_tasks_application.py
This PR fixes a long-standing bug in the `TasksApplication` where the plugins were stopped while the event loop was still running; that seems unlikely to be what any particular application wants, and we've had to work around it in downstream projects. I doubt that this was ever the intended behaviour.
For backwards compatibility, we keep the behaviour where closing the last Tasks windows causes the application to exit. (That behaviour is also worth discussing, but likely in a separate issue.)
Closes #221.
=> Fix TasksApplication lifecycle: don't stop plugins while event loop is running

envisage/plugin.py, envisage/tests/test_plugin.py
This PR updates `Plugin.__repr__` to use the name of the plugin class in place of the currently hard-coded "Plugin" string.
Before:
```python
>>> from envisage.api import CorePlugin
>>> CorePlugin()
Plugin(id='envisage.core', name='Core')
```
After:
```python
>>> from envisage.api import CorePlugin
>>> CorePlugin()
CorePlugin(id='envisage.core', name='Core')
```
Closes #530
=> Fix plugin repr to include the name of the plugin class

envisage/extension_point.py, envisage/extension_point_binding.py, envisage/tests/test_extension_point_binding.py
This PR cleans up some odd use of global state (an extension registry that lived on the `ExtensionPoint` trait type class) that's never used in practice.
In detail:
- `ExtensionPointBinding` no longer uses `ExtensionPoint.extension_registry` as the default extension registry. (Note that `ExtensionPoint.extension_registry` doesn't exist unless it's explicitly injected from some external source.)
- The tests for `bind_extension_point` no longer _inject_ a registry onto the `ExtensionPoint` trait type class, and have been updated to use an explicit registry everywhere
- The `extension_registry` argument to `bind_extension_point` is now required rather than optional
- The `bind` static method on the `ExtensionPoint` trait type, which doesn't support specifying an extension registry, has been …
=> Fix use of ExtensionPoint class for storage of global state

envisage/plugin_manager.py, envisage/tests/test_plugin_manager.py
This PR deprecates use of the `include` and `exclude` traits on the `PluginManager` base class, on the grounds that those traits don't currently work as intended (judging the intention from the tests), and that it's not fully clear how they were intended to work.
The main clients for these traits seem to be the `EggBasketPluginManager` and the `PackagePluginManager`, both of which are now deprecated. The `EggPluginManager` also makes use of this, though it duplicates and overwrites the functionality instead of inheriting it from the `PluginManager` base class.
Technical details:
- the current `include` and `exclude` feed into private methods `_is_included` and `_is_excluded`, which in turn feed into the "protected" method `_include_plugin`, which is presumably intended to be available for …
=> Deprecate the include and exclude traits on PluginManager

envisage/api.py, envisage/extension_point_binding.py, envisage/tests/test_extension_point_binding.py
This PR adds an `unbind_extension_point` function that reverses the effects of `bind_extension_point`. In particular, `unbind_extension_point` removes references to the target `HasTraits` object from global state, allowing that object to be garbage collected in the usual way. (Previously, those references would live until the end of the process.)
- New `unbind_extension_point` function (exported via `envisage.api`), with parameters exactly matching those of `bind_extension_point`. This undoes listener changes, and removes the binding from the global `ExtensionPointBinding._bindings` dictionary.
- New private `ExtensionPointBinding._unbind` method that undoes listener changes. The `_initialize` method has been renamed to `_bind` to match.
- Creation of an `ExtensionPointBinding` object no …
=> Add an unbind_extension_point function

envisage/tests/support.py, envisage/ui/tasks/tests/test_tasks_application.py
We're currently skipping some GUI-using tests in GitHub Actions runs because of an end-of-process segfault caused by a PySide6 bug. That bug is now fixed in the latest release (6.4.3) of PySide6, so this PR tweaks the skip condition so that the tests will only be skipped with versions of PySide6 that are older than 6.4.3.
xref: #476
xref: https://bugreports.qt.io/browse/PYSIDE-2254
=> Don't skip GUI-using tests if we have a recent enough PySide6

CHANGES.rst, pyproject.toml
[Note: PR is intentionally against the `main` branch: there haven't been any feature-level changes since Envisage 7.0, so I'll tag directly from the main branch.]
This PR updates the changelog and version in preparation for a 7.0.2 release.
The ulterior motive is to find out whether our gh-pages documentation build for releases is working as hoped.
=> Add changelog, bump version for Envisage 7.0.2 release

envisage/plugins/event_manager/plugin.py
This tiny PR adds a name to the `EventManagerPlugin`, to prevent a WARNING being logged on computing the `repr` of the plugin.
On main:
```python
Python 3.11.9 (main, Apr  4 2024, 05:29:26) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> logging.basicConfig()
>>> from envisage.plugins.event_manager.api import EventManagerPlugin
>>> plugin = EventManagerPlugin()
>>> plugin
WARNING:envisage.plugin:plugin <envisage.plugins.event_manager.plugin.EventManagerPlugin object at 0x100d8a160> has no name - using <Event Manager Plugin>
EventManagerPlugin(id='envisage.event_manager', name='Event Manager Plugin')
```
On this branch:
```python
Python 3.11.9 (main, Apr  4 2024, 05:29:26) [Clang 15.0.0 …
```
=> Add a name to the EventManagerPlugin

.github/workflows/test-with-pypi.yml, README.rst, etstool.py, pyproject.toml
This PR updates the apptools dependency to apptools >= 5.3, and deals with various pieces of fallout from that change:
Detailed changes:
- require `apptools >= 5.3`, which contains some fixes that we need for some upcoming bugfixes on this repository (see #583)
- require `apptools[preferences]` rather than just plain `apptools`, since version 5.3.0 of `apptools` no longer declares `configobj` as an explicit dependency, and Envisage preferences depend on `configobj`
- similarly, require `configobj` explicitly in `etstool.py`, since EDS doesn't support optional requirements
- require Python >= 3.8, since `apptools` now also requires Python >= 3.8, and `apptools >= 5.3.0` is not available for Python 3.7
=> Require apptools 5.3 or later, Python 3.8 or later

.github/workflows/style-requirements.txt
This PR updates black to silence dependabot warnings about a CVE (though it seems like a CVE that we're very unlikely to run into in practice).
xref: https://github.com/enthought/envisage/security/dependabot/1
=> Update black (CVE)

.github/workflows/style-requirements.txt, CHANGES.rst, pyproject.toml
This PR bumps the package version and updates the changelog in preparation for a 7.0.4 bugfix release.
@flongford Would you have bandwidth to review?
=> Bump version, update changelog for Envisage 7.0.4
