- CHANGES.txt
- MANIFEST.in
- envisage/developer/code_browser/tests/code_browser_test_case.py
- envisage/ui/action/tests/action_manager_builder_test_case.py
- setup.py
- tox.ini
- travis-ci-requirements.txt
- Added tox settings
- Added MANIFEST.in
- Updated setup.py for package data
- Added __init__ for a few test packages
- Fix one local import for tests in py3
> Add tox for testing package install

- envisage/ui/tasks/tasks_application.py
Remove GUI-related imports from head of tasks_application module.
> Remove pyface imports from head of tasks_application.py

- envisage/tests/slice_test_case.py
@corranwebster 
From enthought/traits#115:
- https://github.com/enthought/traits/blob/9e5741bf49943dd37a863d15cdaef32a32cd22cc/traits/trait_handlers.py#L2552
- https://github.com/enthought/traits/blob/9e5741bf49943dd37a863d15cdaef32a32cd22cc/traits/trait_handlers.py#L2495
> Handle case where event.index is None

- envisage/plugins/ipython_kernel/internal_ipkernel.py
- travis-ci-requirements.txt
Moved imports from IPython's package to `ipykernel` package.
> Update imports to ipython 4 architecture.

- envisage/plugins/ipython_kernel/ipython_kernel_plugin.py
This looks like something that should be logged at DEBUG level, not INFO level. (In my mind, INFO-level logging is for informational things that users might be interested in.)
> Downgrade level of a logging message.

- docs/source/conf.py
> DEV: Update sphinx configuration to avoid execfile on file with relative import

- etstool.py
This was an unpushed commit from the #145 branch. I'll merge when CI signs off.
> Fix out-of-date docstring.

- CHANGES.txt
Brings the changelog updates from the `release/4.7.x` branch into master.
> Update changelog for changes in release branch

- docs/source/envisage_core_documentation/gui_application.rst
- docs/source/envisage_core_documentation/workbench.rst
- docs/source/tasks_user_manual/extensibility.rst
- docs/source/tasks_user_manual/layout.rst
- docs/source/tasks_user_manual/menus.rst
- envisage/ui/gui_application.py
- envisage/ui/tasks/tasks_application.py
- envisage/ui/tasks/tasks_plugin.py
- envisage/ui/workbench/workbench_application.py
- envisage/ui/workbench/workbench_plugin.py
Nitpick: the name of the package is Pyface, not PyFace.
Also makes trailing whitespace fixes in the affected files.
> PyFace -> Pyface fixes

- envisage/tests/test_application.py
- envisage/tests/test_extension_point_binding.py
- envisage/tests/test_extension_point_changed.py
- envisage/tests/test_service_registry.py
- envisage/ui/action/tests/test_action_manager_builder.py
There was one use of nose in the package and remove a few comments
mentioning nose
> Remove references and use of nose in pkg

- CHANGES.txt
This PR adds changelog entries for the upcoming 4.8.0 release. I'll make a release branch once this is merged.
> Update changelog for 4.8.0 release.

- envisage/plugins/ipython_kernel/tests/test_internal_ipkernel.py
- envisage/plugins/ipython_kernel/tests/test_ipython_kernel_plugin.py
A couple of test module fixes noted in passing while working on #222. I didn't want to include these in #222 since these are potentially functional changes, while all the changes in #222 should be purely cosmetic.
> Remove an unused import and a useless tearDown.

- envisage/plugins/ipython_kernel/tests/test_ipython_kernel_plugin.py
- envisage/tests/ets_config_patcher.py
- envisage/tests/test_application.py
- envisage/tests/test_plugin.py
> Prevent the test suite from writing to the .enthought directory.

- envisage/ui/single_project/view/project_view.py
@mdickinson, is this the proper way to fix #124?
> Use register_factory() instead of the old adapts()

- envisage/tests/test_slice.py
This PR fixes a couple of tests that fail against the current Traits master, thanks to the fixes in enthought/traits#771.
I've looked at the parts of the actual business logic that deal with list events, and none of them looks as though it would be adversely affected by enthought/traits#771 (indeed, there's at least [one location](https://github.com/enthought/envisage/blob/295b96f9964b15e394772be502ece972f4b7b8cd/envisage/core_plugin.py#L143-L144) that blindly iterates through the items of `event.added`, and that's currently broken under a slice assignment on Traits < 6.0; it'll work as expected under Traits 6.0).
Related: enthought/traits#300.
> Fix tests that fail against Traits master

- CHANGES.rst
- envisage/plugin.py
- envisage/plugins/python_shell/view/python_shell_view.py
- envisage/tests/test_slice.py
- envisage/ui/single_project/project.py
- envisage/ui/single_project/tests/test_clean_strings.py
This PR backports the following PRs from the master branch to the release branch, in preparation for the 4.9.1 release: #255, #253, #252, #250
> Backport bugfix PRs from master to release branch

- CHANGES.rst
This PR brings in changelog updates from #258 to the master branch.
> Update changelog to match the release branch

- setup.cfg
The CI on this PR will fail until all other PRs are merged (and merge conflicts correctly resolved).
But: once #275, #276, #277, #278 and #279 are merged, this PR should pass.
> Exclude single_project from flake8 check; thin out flake8 'ignore' list

- examples/plugins/workbench/AcmeLab/acme/workbench/view/color_view.py
- examples/plugins/workbench/AcmeLabUsingEggs/src/acme.workbench/acme/workbench/view/color_view.py
The import statements have been updated.
> Import from pyface.qt 

- setup.py
This PR contains 2 commits (Don't squash merge!) to set the PRERELEASE to rc1 and flip IS_RELEASED.
> Release candidate 5.0.0rc1

- setup.py
The commit from this PR will be tagged as the release.
> Envisage Release 5.0.0

- etstool.py
The cron job on Travis is currently failing (see https://travis-ci.com/github/enthought/envisage/jobs/447659821) with errors like this:
```
======================================================================
ERROR: envisage.plugins.ipython_kernel.tests.test_ipython_kernel_plugin (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: envisage.plugins.ipython_kernel.tests.test_ipython_kernel_plugin
Traceback (most recent call last):
File "/home/travis/.edm/envs/envisage-test-3.6-null/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
module = self._get_module_from_name(name)
File "/home/travis/.edm/envs/envisage-test-3.6-null/lib/python3.6/unittest/loader.py", line 369, in …
```
> Fix cron job not having all dependencies

- CHANGES.rst
This PR updates the changelog in preparation for the upcoming 6.0.0 major release.
> Update changelog in prep for the upcoming 6.0.0 release

- .readthedocs.yaml
This PR adds a basic configuration file for Read the Docs. These changes are based on enthought/traits#1478. This is one more step towards enthought/ets#69.
> Add RtD config file

- setup.py
Add a Trove classifier for Python 3.10.
> Update classifiers for Python 3.10

- .github/workflows/test-with-pypi.yml
- setup.py
[Extracted from #449]
This PR adds a CI workflow to test Envisage against the latest packages from PyPI rather than the latest EDM packages.
The code was already reviewed by @rahulporuri as part of reviewing #449.
> Add GitHub Actions workflow to test PyPI install

- setup.py
This PR updates the version for continued development towards the next feature release of Envisage.
> Bump version for continued development towards 6.2

- .github/workflows/ets-from-source.yml
- .github/workflows/test-with-edm.yml
- .github/workflows/test-wx.yml
This PR updates the EDM version used to 3.4.0. The intent is mainly to do an indirect test that https://github.com/enthought/setup-edm-action/issues/6 is resolved.
> Update EDM to latest version

- .github/workflows/update-gh-pages-on-release.yml
- CHANGES.rst
- pyproject.toml
This PR fixes the automated release documentation build.
> Fix release doc build
